services:
  kestra:
    image: kestra/kestra:latest
    user: "root"
    command: server standalone
    
    ports:
      - "8080:8080"

    environment:
      KESTRA_QUEUE_TYPE: memory
      KESTRA_REPOSITORY_TYPE: h2
      KESTRA_STORAGE_TYPE: local
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcp-key.json 

      KESTRA_TASKRUNNER_DOCKER_ENABLED: true

    volumes:
      - ../:/app/project 
      - ./storage:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gcp-key.json:/app/gcp-key.json 

    # 👇 ADD THIS FULL CONFIG BLOCK
    configs:
      - source: kestra-config
        target: /app/config/application.yml

configs:
  kestra-config:
    file: ./application.yml